name: zhihurewen
version: 1

cron:
- description: crawl latest news
  url: /operation/fetch?secret=311521
  schedule: "50 */1 * * *"

- description: index latest news
  url: /operation/index?secret=311521
  schedule: "55 */1 * * *"

libraries:
- name: "tornado"
  version: "3.0.0"

- name: "lxml"
  version: "2.3.4"

handlers:
- url: /static/
  static_path: static
  gzip: on

- url: /robots.txt
  static_path: static/robots.txt

- url: /favicon.ico
  static_path: static/favicon.ico