name: zhihurewen
version: 1

cron:
- description: crawl latest news
  url: /operation/fetch
  schedule: "50 */1 * * *"
  login: admin@admin

- description: index latest news
  url: /operation/index
  schedule: "55 12,16,22 * * *"
  login: admin@admin

libraries:
- name: "tornado"
  version: "3.0.0"

- name: "lxml"
  version: "2.3.4"

handlers:
- url: /static/
  static_path: static
  gzip: on

- url: /robots.txt
  static_path: static/robots.txt

- url: /favicon.ico
  static_path: static/favicon.ico